### ISSUE TITLE
Escribe tu nombre completo

### ISSUE THREAD

**Issue by lasr21** [gitcommituyu/grupo3_2023#1]
Escribe tu nombre completo para el certificado :octocat:

**Comment by CSRGCMTB** [comment]
Santiago Gabriel Miranda Blanco

**Comment by BorgesJahn** [comment]
Jahn Hamir Borges Quesada

**Comment by FacuPort0** [comment]
Facundo Tabaré Portillo Corbo

**Comment by Cristo2001G** [comment]
Cristofer Garcia

**Comment by AlexisSosaOjeda** [comment]
Alexis Sosa Ojeda

**Comment by PaZamora58** [comment]
Pablo Zamora

**Comment by IsmaelHernandezUY** [comment]
Aarón Ismael Rivero Hernández

**Comment by GReherman** [comment]
Guillermo Reherman Armstrong

**Comment by AngelAleman15** [comment]
Ángel Agustín Alemán Sánchez

**Comment by Mily-Ramallo** [comment]
Milagros Ramallo Fernández

**Comment by GCGiuliana94** [comment]
Giuliana Casavieja González

**Comment by MicayaCoronel** [comment]
Jehoseba Micaya Giménez Coronel

**Comment by Sabri-G** [comment]
Sabrina Evelyn García Aguiar

**Comment by BDMaggio** [comment]
Bruno Jesus DI Maggio Olivera

**Comment by FJTorrecillas** [comment]
Francisco Joel Torrecillas Rodriguez

**Comment by Fedefernandez818** [comment]
Federico Ezequiel Fernández Pérez

**Comment by JFresnedoso** [comment]
Jean Paul Fresnedoso Fernández

**Comment by Demiancard** [comment]
Demian Cardona Martínez

**Comment by JavaREPORTER** [comment]
Anthony Gomez Ismael Cagnola

**Comment by AlexanderRosaFa** [comment]
Alexander Ezequiel Rosa Farías

**Comment by CataMGR** [comment]
Catalina Magalí Gamarra Rodríguez

**Comment by sheralR** [comment]
Sheral Junior Rodriguez Rosa

**Comment by NickGmenez** [comment]
Nicolás Francisco Giménez Muniz

**Comment by ZoeGonz16** [comment]
Zoe Agustina González Meneses

**Comment by SebastianIbarborou** [comment]
Pablo Sebastián Ibarborou González

**Comment by mathiasgab** [comment]
Mathias Gabriel Pereyra Catarino

**Comment by AlanRodriguezMO** [comment]
Alan Rodriguez Mathui Olivera

**Comment by AlanRodriguezMO** [comment]
Alan Mathiu Rodriguez Olivera

**Comment by lasr21** [comment]
Pier Nicolas Aires Silva
